using System.Collections.Immutable;
using System.Globalization;
using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.Text;

namespace Orkis.Tools.Generator;

internal static class Emitter
{
    private static readonly DiagnosticDescriptor ContainerNotPartial = new(
        id: "ORK001",
        title: "Tool container must be partial",
        messageFormat: "Type '{0}' contains [OrkisTool] methods and must be declared partial",
        category: "Orkis.Tools",
        defaultSeverity: DiagnosticSeverity.Error,
        isEnabledByDefault: true
    );

    private static readonly DiagnosticDescriptor ContainerIsNested = new(
        id: "ORK002",
        title: "Tool container must be top-level",
        messageFormat: "Type '{0}' contains [OrkisTool] methods and must not be nested in another type",
        category: "Orkis.Tools",
        defaultSeverity: DiagnosticSeverity.Error,
        isEnabledByDefault: true
    );

    public static void Emit(SourceProductionContext context, ImmutableArray<ToolModel> models)
    {
        foreach (var group in models.GroupBy(static m => (m.Namespace, m.TypeName)))
        {
            var tools = group.ToList();
            var first = tools[0];

            if (!first.TypeIsPartial)
            {
                context.ReportDiagnostic(Diagnostic.Create(ContainerNotPartial, Location.None, first.TypeName));
                continue;
            }

            if (first.TypeIsNested)
            {
                context.ReportDiagnostic(Diagnostic.Create(ContainerIsNested, Location.None, first.TypeName));
                continue;
            }

            var hintName = (first.Namespace is null ? "" : first.Namespace + ".") + first.TypeName + ".OrkisTools.g.cs";
            context.AddSource(hintName, SourceText.From(EmitType(first, tools), Encoding.UTF8));
        }
    }

    private static string EmitType(ToolModel first, System.Collections.Generic.List<ToolModel> tools)
    {
        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("#nullable enable");
        sb.AppendLine();
        if (first.Namespace is not null)
        {
            sb.Append("namespace ").Append(first.Namespace).AppendLine(";");
            sb.AppendLine();
        }

        sb.Append("partial class ").AppendLine(first.TypeName);
        sb.AppendLine("{");

        foreach (var tool in tools)
        {
            EmitFactory(sb, tool);
            sb.AppendLine();
        }

        EmitAggregate(sb, first, tools);

        foreach (var tool in tools)
        {
            sb.AppendLine();
            EmitToolClass(sb, tool);
        }

        sb.AppendLine("}");
        return sb.ToString();
    }

    private static void EmitFactory(StringBuilder sb, ToolModel tool)
    {
        var modifier = tool.MethodIsStatic ? "static " : "";
        var argument = tool.MethodIsStatic ? "" : "this";
        sb.Append("    /// <summary>Creates the generated tool for <see cref=\"")
            .Append(tool.MethodName)
            .AppendLine("\"/>.</summary>");
        sb.Append("    public ")
            .Append(modifier)
            .Append("global::Orkis.Tools.ITool Create")
            .Append(FactoryBaseName(tool))
            .Append("Tool() => new ")
            .Append(ToolClassName(tool))
            .Append('(')
            .Append(argument)
            .AppendLine(");");
    }

    private static void EmitAggregate(
        StringBuilder sb,
        ToolModel first,
        System.Collections.Generic.List<ToolModel> tools
    )
    {
        var allStatic = tools.All(static t => t.MethodIsStatic);
        var modifier = first.TypeIsStatic || allStatic ? "static " : "";
        sb.AppendLine("    /// <summary>Creates all tools generated for this type.</summary>");
        sb.Append("    public ")
            .Append(modifier)
            .AppendLine(
                "global::System.Collections.Generic.IReadOnlyList<global::Orkis.Tools.ITool> CreateOrkisTools() =>"
            );
        sb.Append("        new global::Orkis.Tools.ITool[] { ");
        sb.Append(string.Join(", ", tools.Select(static t => "Create" + FactoryBaseName(t) + "Tool()")));
        sb.AppendLine(" };");
    }

    private static void EmitToolClass(StringBuilder sb, ToolModel tool)
    {
        var className = ToolClassName(tool);
        var isAsync =
            tool.ReturnKind
            is ReturnKind.TaskVoid
                or ReturnKind.TaskString
                or ReturnKind.TaskOther
                or ReturnKind.ValueTaskString
                or ReturnKind.ValueTaskOther;

        sb.AppendLine(
            "    [global::System.CodeDom.Compiler.GeneratedCodeAttribute(\"Orkis.Tools.Generator\", \"1.0.0\")]"
        );
        sb.Append("    private sealed class ").Append(className).AppendLine(" : global::Orkis.Tools.ITool");
        sb.AppendLine("    {");

        // Descriptor with compile-time schema.
        sb.AppendLine(
            "        private static readonly global::Orkis.Tools.ToolDescriptor s_descriptor = new global::Orkis.Tools.ToolDescriptor"
        );
        sb.AppendLine("        {");
        sb.Append("            Name = ").Append(Literal(tool.ToolName)).AppendLine(",");
        sb.Append("            Description = ").Append(Literal(tool.Description)).AppendLine(",");
        sb.Append("            ParametersSchema = global::System.Text.Json.JsonDocument.Parse(")
            .Append(Literal(BuildSchemaJson(tool)))
            .AppendLine(").RootElement,");
        sb.Append("            Risk = (global::Orkis.Tools.ToolRisk)")
            .Append(tool.Risk.ToString(CultureInfo.InvariantCulture))
            .AppendLine(",");
        sb.AppendLine("        };");
        sb.AppendLine();

        if (!tool.MethodIsStatic)
        {
            sb.Append("        private readonly ").Append(tool.TypeName).AppendLine(" _owner;");
            sb.AppendLine();
            sb.Append("        public ")
                .Append(className)
                .Append('(')
                .Append(tool.TypeName)
                .AppendLine(" owner) => _owner = owner;");
        }
        else
        {
            sb.Append("        public ").Append(className).AppendLine("() { }");
        }

        sb.AppendLine();
        sb.AppendLine("        public global::Orkis.Tools.ToolDescriptor Descriptor => s_descriptor;");
        sb.AppendLine();

        sb.Append("        public ")
            .Append(isAsync ? "async " : "")
            .AppendLine("global::System.Threading.Tasks.Task<global::Orkis.Tools.ToolResult> InvokeAsync(");
        sb.AppendLine("            global::Orkis.Tools.ToolCall toolCall,");
        sb.AppendLine("            global::System.Threading.CancellationToken cancellationToken = default");
        sb.AppendLine("        )");
        sb.AppendLine("        {");
        sb.AppendLine("            global::System.ArgumentNullException.ThrowIfNull(toolCall);");
        if (tool.Parameters.Any(static p => p.Kind != ParamKind.CancellationToken))
        {
            sb.AppendLine("            var __arguments = toolCall.Arguments;");
        }

        foreach (var parameter in tool.Parameters)
        {
            EmitBinding(sb, tool, parameter);
        }

        var call = BuildInvocation(tool);
        EmitReturn(sb, tool, call, isAsync);

        sb.AppendLine("        }");
        sb.AppendLine("    }");
    }

    private static void EmitBinding(StringBuilder sb, ToolModel tool, ParameterModel parameter)
    {
        if (parameter.Kind == ParamKind.CancellationToken)
        {
            return;
        }

        var property = "__" + parameter.Name + "Property";
        var read = ReadExpression(property, tool, parameter);

        if (parameter.IsOptional)
        {
            sb.Append("            var __")
                .Append(parameter.Name)
                .Append(" = __arguments.TryGetProperty(")
                .Append(Literal(parameter.Name))
                .Append(", out var ")
                .Append(property)
                .Append(") ? ")
                .Append(read)
                .Append(" : ")
                .Append(parameter.DefaultLiteral ?? "default!")
                .AppendLine(";");
        }
        else
        {
            sb.Append("            if (!__arguments.TryGetProperty(")
                .Append(Literal(parameter.Name))
                .Append(", out var ")
                .Append(property)
                .AppendLine("))");
            sb.AppendLine("            {");
            sb.Append("                throw new global::System.ArgumentException(")
                .Append(Literal($"Tool '{tool.ToolName}' is missing required argument '{parameter.Name}'."))
                .AppendLine(");");
            sb.AppendLine("            }");
            sb.Append("            var __").Append(parameter.Name).Append(" = ").Append(read).AppendLine(";");
        }
    }

    private static string ReadExpression(string property, ToolModel tool, ParameterModel parameter) =>
        parameter.Kind switch
        {
            ParamKind.String => property
                + ".GetString() ?? throw new global::System.ArgumentException("
                + Literal($"Argument '{parameter.Name}' of tool '{tool.ToolName}' must be a string.")
                + ")",
            ParamKind.Bool => property + ".GetBoolean()",
            ParamKind.Int32 => property + ".GetInt32()",
            ParamKind.Int64 => property + ".GetInt64()",
            ParamKind.Double => property + ".GetDouble()",
            ParamKind.Single => property + ".GetSingle()",
            ParamKind.Decimal => property + ".GetDecimal()",
            ParamKind.Enum => "global::System.Enum.Parse<"
                + parameter.TypeFullName
                + ">("
                + property
                + ".GetString() ?? \"\", ignoreCase: true)",
            _ => "global::System.Text.Json.JsonSerializer.Deserialize<"
                + parameter.TypeFullName
                + ">("
                + property
                + ", global::System.Text.Json.JsonSerializerOptions.Web)!",
        };

    private static string BuildInvocation(ToolModel tool)
    {
        var arguments = string.Join(
            ", ",
            tool.Parameters.Select(static p =>
                p.Kind == ParamKind.CancellationToken ? "cancellationToken" : "__" + p.Name
            )
        );
        var target = tool.MethodIsStatic ? tool.MethodName : "_owner." + tool.MethodName;
        return target + "(" + arguments + ")";
    }

    private static void EmitReturn(StringBuilder sb, ToolModel tool, string call, bool isAsync)
    {
        const string serializeResult =
            "global::System.Text.Json.JsonSerializer.Serialize(__result, global::System.Text.Json.JsonSerializerOptions.Web)";

        string content;
        switch (tool.ReturnKind)
        {
            case ReturnKind.Void:
                sb.Append("            ").Append(call).AppendLine(";");
                content = "\"\"";
                break;
            case ReturnKind.TaskVoid:
                sb.Append("            await ").Append(call).AppendLine(".ConfigureAwait(false);");
                content = "\"\"";
                break;
            case ReturnKind.String:
            case ReturnKind.Other:
                sb.Append("            var __result = ").Append(call).AppendLine(";");
                content = tool.ReturnKind == ReturnKind.String ? "__result ?? \"\"" : serializeResult;
                break;
            default:
                sb.Append("            var __result = await ").Append(call).AppendLine(".ConfigureAwait(false);");
                content = tool.ReturnKind is ReturnKind.TaskString or ReturnKind.ValueTaskString
                    ? "__result ?? \"\""
                    : serializeResult;
                break;
        }

        var resultExpression =
            "new global::Orkis.Tools.ToolResult { ToolCallId = toolCall.Id, Content = " + content + " }";
        sb.Append("            return ")
            .Append(
                isAsync ? resultExpression : "global::System.Threading.Tasks.Task.FromResult(" + resultExpression + ")"
            )
            .AppendLine(";");
    }

    private static string BuildSchemaJson(ToolModel tool)
    {
        var sb = new StringBuilder("{\"type\":\"object\"");
        var parameters = tool.Parameters.Where(static p => p.Kind != ParamKind.CancellationToken).ToList();
        if (parameters.Count > 0)
        {
            sb.Append(",\"properties\":{");
            for (var i = 0; i < parameters.Count; i++)
            {
                if (i > 0)
                {
                    sb.Append(',');
                }

                sb.Append('"').Append(EscapeJson(parameters[i].Name)).Append("\":");
                AppendPropertySchema(sb, parameters[i]);
            }

            sb.Append('}');

            var required = parameters.Where(static p => !p.IsOptional).ToList();
            if (required.Count > 0)
            {
                sb.Append(",\"required\":[");
                sb.Append(string.Join(",", required.Select(static p => "\"" + EscapeJson(p.Name) + "\"")));
                sb.Append(']');
            }
        }

        sb.Append('}');
        return sb.ToString();
    }

    private static void AppendPropertySchema(StringBuilder sb, ParameterModel parameter)
    {
        sb.Append('{');
        var hasType = true;
        switch (parameter.Kind)
        {
            case ParamKind.String:
                sb.Append("\"type\":\"string\"");
                break;
            case ParamKind.Bool:
                sb.Append("\"type\":\"boolean\"");
                break;
            case ParamKind.Int32:
            case ParamKind.Int64:
                sb.Append("\"type\":\"integer\"");
                break;
            case ParamKind.Double:
            case ParamKind.Single:
            case ParamKind.Decimal:
                sb.Append("\"type\":\"number\"");
                break;
            case ParamKind.Enum:
                sb.Append("\"type\":\"string\",\"enum\":[");
                sb.Append(string.Join(",", parameter.EnumValues.Select(static v => "\"" + EscapeJson(v) + "\"")));
                sb.Append(']');
                break;
            default:
                hasType = false;
                break;
        }

        if (parameter.Description is { } description)
        {
            if (hasType)
            {
                sb.Append(',');
            }

            sb.Append("\"description\":\"").Append(EscapeJson(description)).Append('"');
        }

        sb.Append('}');
    }

    private static string EscapeJson(string value)
    {
        var sb = new StringBuilder(value.Length);
        foreach (var c in value)
        {
            switch (c)
            {
                case '"':
                    sb.Append("\\\"");
                    break;
                case '\\':
                    sb.Append("\\\\");
                    break;
                case '\n':
                    sb.Append("\\n");
                    break;
                case '\r':
                    sb.Append("\\r");
                    break;
                case '\t':
                    sb.Append("\\t");
                    break;
                default:
                    if (c < ' ')
                    {
                        sb.Append("\\u").Append(((int)c).ToString("x4", CultureInfo.InvariantCulture));
                    }
                    else
                    {
                        sb.Append(c);
                    }

                    break;
            }
        }

        return sb.ToString();
    }

    private static string FactoryBaseName(ToolModel tool) =>
        tool.MethodName.Length > 5 && tool.MethodName.EndsWith("Async", System.StringComparison.Ordinal)
            ? tool.MethodName.Substring(0, tool.MethodName.Length - 5)
            : tool.MethodName;

    private static string ToolClassName(ToolModel tool) => "__" + tool.MethodName + "Tool";

    private static string Literal(string value) => SymbolDisplay.FormatLiteral(value, quote: true);
}
