using Orkis.Tools;

namespace Orkis.Host;

/// <summary>Simple read-only tools, generated by the Orkis source generator.</summary>
public sealed partial class DemoTools
{
    [OrkisTool(Description = "Gets the current UTC date and time.", Risk = ToolRisk.ReadOnly)]
    public static string GetUtcNow() => DateTimeOffset.UtcNow.ToString("u");

    [OrkisTool(Description = "Rolls dice and reports each result.", Risk = ToolRisk.ReadOnly)]
    public static string RollDice(
        [OrkisToolParameter("Number of dice to roll.")] int count = 1,
        [OrkisToolParameter("Sides per die.")] int sides = 6
    )
    {
        var rolls = Enumerable
            .Range(0, Math.Clamp(count, 1, 100))
            .Select(_ => Random.Shared.Next(1, Math.Max(2, sides) + 1))
            .ToList();
        return string.Join(", ", rolls);
    }
}
